name: 'Assemble APK'
description: "Assemble APK and Upload artifact to GitHub"
inputs:
  build-type:
    description: "Build type"
    required: true
  signing-files:
    description: 'Base64 encoded string of the file'
    required: false
    default: ""
  retention-days:
    description: 'Remove artifacts after the specified number of days'
    required: false
    default: "1"
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Decode secret files
      if: ${{ inputs.build-type == 'Release' && inputs.signing-files != '' }}
      id: decode_secret_files
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'signing.tar.gz'
        fileDir: './config'
        encodedString: ${{ inputs.signingFiles }}

    - name: Extract secret files
      if: ${{ inputs.build-type == 'Release' && inputs.signing-files != '' }}
      shell: bash
      run: |
        tar xf ${{ steps.decode_secret_files.outputs.filePath }} --directory ./config

    - name: Assemble apk
      run: ./gradlew assemble${{ inputs.buildType }} --stacktrace --scan
      shell: bash

    - name: Upload Outputs
      uses: actions/upload-artifact@v4
      with:
        path: |
          app/build/outputs/apk/
          app/build/generated/res/google-services/
        retention-days: ${{ inputs.retentionDays }}
