name: 'Assemble APK'
description: "Assemble APK and Upload artifact to GitHub"
inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  build-type:
    description: "Build type"
    required: true
  signing-files:
    description: 'Base64 encoded string of the file'
    required: false
    default: ""
  upload-files:
    description: 'Upload apk files'
    required: false
    default: "true"
  retention-days:
    description: 'Remove artifacts after the specified number of days'
    required: false
    default: "1"
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Decode secret files
      if: ${{ inputs.build-type == 'Release' && inputs.signing-files != '' }}
      id: decode_secret_files
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'signing.tar.gz'
        fileDir: './config'
        encodedString: ${{ inputs.signing-files }}

    - name: Extract secret files
      if: ${{ inputs.build-type == 'Release' && inputs.signing-files != '' }}
      shell: bash
      run: |
        tar xf ${{ steps.decode_secret_files.outputs.filePath }} --directory ./config

    - name: Assemble apk
      run: ./gradlew assemble${{ inputs.buildType }} --stacktrace --scan
      shell: bash

    - name: Upload Outputs
      if: ${{ inputs.upload-files == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: assemble${{ inputs.build-type }}-${{ inputs.id }}
        path: |
          ./**/**/build/outputs/aar
          ./**/**/build/generated/res/google-services
          ./**/build/outputs/apk
          ./**/build/outputs/aar
          ./**/build/generated/res/google-services
        retention-days: ${{ inputs.retention-days }}
