object Modules {
  const val libraryKotlin = ":libraries:kotlin"
  const val libraryCoroutines = ":libraries:coroutines"
  const val libraryBase = ":libraries:base"
  const val libraryAndroid = ":libraries:android"
  const val libraryPreferences = ":libraries:preferences"
  const val libraryRx = ":libraries:rx"
  const val libraryRetrofit = ":libraries:retrofit"
  const val libraryPagination = ":libraries:pagination"
  const val libraryPaginationRx = ":libraries:pagination-rx"
  const val libraryThreeten = ":libraries:threeten"
  const val libraryGlide = ":libraries:glide"
  const val libraryTest = ":libraries:test-unit"
  const val libraryAndroidTest = ":libraries:test-android"
}
