object Modules {
  const val libraryAndroid = ":libraries:android"
  const val libraryBase = ":libraries:base"
  const val libraryCoroutines = ":libraries:coroutines"
  const val libraryFirebase = ":libraries:firebase"
  const val libraryGlide = ":libraries:glide"
  const val libraryKoin = ":libraries:koin"
  const val libraryOkHttp3 = ":libraries:okhttp3"
  const val libraryPagination = ":libraries:pagination"
  const val libraryPaginationCo = ":libraries:pagination-co"
  const val libraryPaginationRx = ":libraries:pagination-rx"
  const val libraryPermissions = ":libraries:permissions"
  const val libraryPreferences = ":libraries:preferences"
  const val libraryRetrofit = ":libraries:retrofit"
  const val libraryRetrofitCo = ":libraries:retrofit-co"
  const val libraryRetrofitRx = ":libraries:retrofit-rx"
  const val libraryRx = ":libraries:rx"
  const val libraryAndroidTest = ":libraries:test-android"
  const val libraryTest = ":libraries:test-unit"
  const val libraryTestCo = ":libraries:test-unit-co"
  const val libraryTestRx = ":libraries:test-unit-rx"
  const val libraryThreeten = ":libraries:threeten"
}
