object Modules {
    const val libraryAndroid = ":libraries:android"
    const val libraryAndroidTest = ":libraries:android-test"
    const val libraryCoroutines = ":libraries:coroutines"
    const val libraryCoroutinesTest = ":libraries:coroutines-test"
    const val libraryGlide = ":libraries:glide"
    const val libraryOkHttp3 = ":libraries:okhttp3"
    const val libraryPagination = ":libraries:pagination"
    const val libraryPaginationCo = ":libraries:pagination-co"
    const val libraryPaginationRx = ":libraries:pagination-rx"
    const val libraryPermissions = ":libraries:permissions"
    const val libraryPreferences = ":libraries:preferences"
    const val libraryRetrofit = ":libraries:retrofit"
    const val libraryRetrofitCo = ":libraries:retrofit-co"
    const val libraryRetrofitRx = ":libraries:retrofit-rx"
    const val libraryRx = ":libraries:rx"
    const val libraryRxTest = ":libraries:rx-test"
    const val libraryThreeten = ":libraries:threeten"
}
