name: 'Bump module version'
description: "Bump module version"

inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  module:
    description: 'Module name'
    required: true
  patch:
    description: 'Increase patch version'
    required: false
    default: 'false'
  minor:
    description: 'Increase minor version'
    required: false
    default: 'false'
  major:
    description: 'Increase major version'
    required: false
    default: 'false'

outputs:
  version:
    description: "Module bumped version"
    value: ${{ steps.get-version.outputs.value }}

runs:
  using: "composite"
  steps:
    - name: Increase patch version
      if: inputs.patch == 'true'
      run: |
        ./gradlew :${{ inputs.module }}:increasePatchVersion --no-configuration-cache
      shell: bash

    - name: Increase minor version
      if: inputs.minor == 'true'
      run: |
        ./gradlew :${{ inputs.module }}:increaseMinorVersion --no-configuration-cache
      shell: bash

    - name: Increase major version
      if: inputs.major == 'true'
      run: |
        ./gradlew :${{ inputs.module }}:increaseMajorVersion --no-configuration-cache
      shell: bash

    - name: Get version
      id: get-version
      run: |
        echo "Get current version from ${{ inputs.module }}"
        VERSION=$(./gradlew -q :${{ inputs.module }}:getVersion | tail -n 1)
        echo "${{ inputs.module }} module has been updated to version $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "value=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash
