name: 'Bump module version'
description: "Bump module version"

inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  module:
    description: 'Module name'
    required: false
    default: "app"
  version:
    description: 'Bump module version'
    required: false
    default: 'patch'

outputs:
  version:
    description: "Module bumped version"
    value: ${{ steps.get-version.outputs.value }}

runs:
  using: "composite"
  steps:

    - name: Increase patch version
      if: inputs.version == 'patch'
      run: |
        ./gradlew :${{ inputs.module }}:increasePatchVersion --no-configuration-cache
      shell: bash

    - name: Increase minor version
      if: inputs.version == 'minor'
      run: |
        ./gradlew :${{ inputs.module }}:increaseMinorVersion --no-configuration-cache
      shell: bash

    - name: Increase major version
      if: inputs.version == 'major'
      run: |
        ./gradlew :${{ inputs.module }}:increaseMajorVersion --no-configuration-cache
      shell: bash

    - name: Get version
      id: get-version
      uses: ./.github/actions/get_version
      with:
        module: ${{ inputs.module }}

    - name: Module has been updated
      run: |
        echo "${{ inputs.module }} module has been updated to version ${{ steps.get-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
      shell: bash
