name: 'Bump module version'
description: "Bump module version"

inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  module:
    description: 'Module name'
    required: true
  force-bump:
    description: 'Force the bump version'
    required: false
    default: "false"

outputs:
  version:
    description: "Module bumped version"
    value: ${{ steps.get-version.outputs.value }}

runs:
  using: "composite"
  steps:
    - name: Get module info
      id: get-module-info
      uses: ./.github/actions/module_info
      with:
        module: ${{ inputs.module }}

    - name: Get pull request info
      id: get-pr-info
      uses: ./.github/actions/pull_request_info

    - name: Increase patch version
      if: (steps.get-module-info.outputs.has-changes == 'true' && steps.get-pr-info.outputs.is-patch == 'true') || inputs.force-bump == 'true'
      run: |
        ./gradlew :${{ inputs.module }}:increasePatchVersion --no-configuration-cache
      shell: bash

    - name: Increase minor version
      if: steps.get-module-info.outputs.has-changes == 'true' && steps.get-pr-info.outputs.is-minor == 'true'
      run: |
        ./gradlew :${{ inputs.module }}:increaseMinorVersion --no-configuration-cache
      shell: bash

    - name: Increase major version
      if: steps.get-module-info.outputs.has-changes == 'true' && steps.get-pr-info.outputs.is-major == 'true'
      run: |
        ./gradlew :${{ inputs.module }}:increaseMajorVersion --no-configuration-cache
      shell: bash

    - name: Get version
      if: inputs.force-bump == 'true' ||
          ( steps.get-module-info.outputs.has-changes == 'true' && 
          ( steps.get-pr-info.outputs.is-patch == 'true' || steps.get-pr-info.outputs.is-minor == 'true' || steps.get-pr-info.outputs.is-major == 'true' ) )
      id: get-version
      run: |
        echo "Get current version from ${{ inputs.module }}"
        VERSION=$(./gradlew -q :${{ inputs.module }}:getVersion | tail -n 1)
        echo "${{ inputs.module }} module has been updated to version $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "value=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash
