name: 'Launch Unit tests'
description: "Launch Unit tests and upload outputs to GitHub"
inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  retention-days:
    description: 'Remove artifacts after the specified number of days'
    required: false
    default: "1"
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Unit tests
      run: ./gradlew testDebugUnitTest --stacktrace --scan
      shell: bash

    - name: Upload Outputs
      uses: actions/upload-artifact@v4
      with:
        name: outputs-unit-tests-${{ inputs.id }}
        path: |
          ./**/build/reports/tests/
          ./**/build/outputs/unit_test_code_coverage/
        retention-days: ${{ inputs.retention-days }}
