name: 'Launch Unit tests'
description: "Launch Unit tests and upload outputs to GitHub"
inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  cache-disabled:
    description: 'Cache'
    required: false
    default: "false"
  retention-days:
    description: 'Remove artifacts after the specified number of days'
    required: false
    default: "1"
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Unit tests
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: testDebugUnitTest --no-configuration-cache --stacktrace --scan
        cache-disabled: ${{ inputs.cache-disabled == 'true' }}

    - name: Upload Outputs
      uses: actions/upload-artifact@v4
      with:
        name: outputs-unit-tests-${{ inputs.id }}
        path: |
          ./**/build/reports/tests/
          ./**/build/outputs/unit_test_code_coverage/
        retention-days: ${{ inputs.retention-days }}
