name: 'Check code (detekt)'
description: "Checking the code via Detekt"
inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  retention-days:
    description: 'Remove artifacts after the specified number of days'
    required: false
    default: "1"
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Check code via Detekt
      run: ./gradlew detekt --stacktrace --scan
      shell: bash

    - name: Upload Outputs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: outputs-detekt-${{ inputs.id }}
        path: |
          ./**/build/reports/detekt/
        retention-days: ${{ inputs.retention-days }}
