name: 'Generate reports'
description: "Generate jacoco reports and upload to codecov"
inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  token:
    description: 'Codecov token'
    required: true
  retention-days:
    description: 'Remove artifacts after the specified number of days'
    required: false
    default: "1"
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Load unit tests outputs
      uses: actions/download-artifact@v4
      with:
        name: outputs-unit-tests-${{ inputs.id }}
#        if-no-files-found: warn

#  https://github.com/actions/upload-artifact/issues/255
#    - name: Load instrumental tests outputs
#      uses: actions/download-artifact@v4
#      with:
#        name: outputs-android-tests
#        if-no-files-found: warn

    - name: Jacoco Reports
      run: ./gradlew coverageReport --stacktrace --scan
      shell: bash

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: reports-jacoco-${{ inputs.id }}
        path: |
          ./**/build/reports/jacoco.xml
          ./**/build/reports/jacoco/
        retention-days: ${{ inputs.retention-days }}

    - name: Uploading reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ inputs.token }}
