name: 'Common machine setup'
description: "Prepares the machine"
inputs:
  java-version:
    description: "Java version"
    required: true
    default: '17'
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }} and Gradle cache
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
