# This is a basic workflow to help you get started with Actions

name: Continuous Integration (Code coverage)

# Workflow events: Controls when the action will run.
# More info: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Increment this to invalidate the cache.
  CACHE_VERSION: 1
  # Enable debug for the `gradle-build-action` cache operations
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
  # Retention days used for output files
  RETENTION_DAYS: 3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  info:
    name: Workflow Information
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Basic Information
        uses: ./.github/actions/info

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Unit tests
        uses: ./.github/actions/unit_tests
        with:
          retention-days: ${{ env.RETENTION_DAYS }}

  reports:
    needs: [ test ]
    if: success()
    name: Generate reports
    runs-on: ubuntu-latest
    environment: release_environment

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Generate jacoco reports and upload to codecov
        uses: ./.github/actions/reports
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          retention-days: ${{ env.RETENTION_DAYS }}
