# This is a basic workflow to help you get started with Actions

name: Continuous Integration (Publish)

# Workflow events: Controls when the action will run.
# More info: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      module:
        description: 'Module name'
        required: true
        default: 'all'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Increment this to invalidate the cache.
  CACHE_VERSION: 1
  # Enable debug for the `gradle-build-action` cache operations
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
  # Retention days used for output files
  RETENTION_DAYS: 1
  # Build type
  BUILD_TYPE: "Release"
  # Artifact type
  ARTIFACT_TYPE: "APK"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  info:
    name: Workflow Information
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Basic Information
        uses: ./.github/actions/info

  checkstyle:
    name: Check code (detekt)
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Check code via Detekt
        uses: ./.github/actions/checkstyle
        with:
          retention-days: ${{ env.RETENTION_DAYS }}

  build:
    needs: [ checkstyle ]
    if: success()
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Assemble ${{ env.BUILD_TYPE }}
        uses: ./.github/actions/assemble
        with:
          build-type: ${{ env.BUILD_TYPE }}
          artifact-type: ${{ env.ARTIFACT_TYPE }}
          retention-days: ${{ env.RETENTION_DAYS }}

  test:
    needs: [ build ]
    if: success()
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Unit tests
        uses: ./.github/actions/unit_tests
        with:
          build-type: ${{ env.BUILD_TYPE }}
          retention-days: ${{ env.RETENTION_DAYS }}

  publish:
    needs: [ test ]
    name: Publish to Sonatype
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        module: [
          "libraries:android",
          "libraries:android-binding",
          "libraries:android-compose",
          "libraries:android-test",
          "libraries:core",
          "libraries:coroutines",
          "libraries:coroutines-test",
          "libraries:network",
          "libraries:network-rx",
          "libraries:pagination",
          "libraries:pagination-co",
          "libraries:pagination-rx",
          "libraries:permissions",
          "libraries:preferences",
          "libraries:rx",
          "libraries:rx-test",
          "libraries:threeten",
          "libraries:threeten-test",
        ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Get module info
        id: get-module-info
        uses: ./.github/actions/module_info
        with:
          module: ${{ matrix.module }}

      - name: Publish module library
        if: steps.get-module-info.outputs.has-changes == 'true' ||
          ( github.event.inputs.module == matrix.module || github.event.inputs.module == 'all' )
        uses: ./.github/actions/publish_module
        with:
          module: ${{ matrix.module }}
          sonatype-id: ${{ secrets.OSSRH_ID }}
          sonatype-username: ${{ secrets.OSSRH_USERNAME }}
          sonatype-password: ${{ secrets.OSSRH_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-id: ${{ secrets.SIGNING_KEY_ID }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
