# This is a basic workflow to help you get started with Actions

name: Continuous Integration (Publish)

# Workflow events: Controls when the action will run.
# More info: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    types:
      - closed
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      module:
        description: 'Module name'
        required: true
        default: 'all'
      max-parallel:
        description: 'Parallel threads'
        required: true
        type: number
        default: 1

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Increment this to invalidate the cache.
  CACHE_VERSION: 1
  # Enable debug for the `gradle-build-action` cache operations
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
  # Retention days used for output files
  RETENTION_DAYS: 3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  info:
    name: Workflow Information
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Basic Information
        uses: ./.github/actions/info

  checkstyle:
    name: Check code (detekt)
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Check code via Detekt
        uses: ./.github/actions/checkstyle
        with:
          retention-days: ${{ env.RETENTION_DAYS }}

  build:
    needs: [ checkstyle ]
    if: success()
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildType: [ "Release" ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Assemble ${{ matrix.buildType }}
        uses: ./.github/actions/assemble
        with:
          build-type: ${{ matrix.buildType }}
          retention-days: ${{ env.RETENTION_DAYS }}

  test:
    needs: [ checkstyle ]
    if: success()
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Unit tests
        uses: ./.github/actions/unit_tests
        with:
          retention-days: ${{ env.RETENTION_DAYS }}

  publish:
    needs: [ build, test ]
    name: Publish to Sonatype
    runs-on: ubuntu-latest
    strategy:
      max-parallel: ${{ fromJson(github.event.inputs.max-parallel) }}
      matrix:
        module: [
          "libraries:android",
          "libraries:android-binding",
          "libraries:android-compose",
          "libraries:android-test",
          "libraries:core",
          "libraries:coroutines",
          "libraries:coroutines-test",
          "libraries:network",
          "libraries:network-rx",
          "libraries:pagination",
          "libraries:pagination-co",
          "libraries:pagination-rx",
          "libraries:permissions",
          "libraries:preferences",
          "libraries:rx",
          "libraries:rx-test",
          "libraries:threeten",
          "libraries:threeten-test",
        ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup machine
        uses: ./.github/actions/setup

      - name: Bump module version
        id: bump-module-version
        uses: ./.github/actions/bump_version
        with:
          module: ${{ matrix.module }}
          force-bump: ${{ github.event.inputs.module == matrix.module || github.event.inputs.module == 'all' }}

      - name: Publish module library
        if: steps.bump-module-version.outputs.version != ''
        uses: ./.github/actions/publish_module
        with:
          module: ${{ matrix.module }}
          sonatype-id: ${{ secrets.OSSRH_ID }}
          sonatype-username: ${{ secrets.OSSRH_USERNAME }}
          sonatype-password: ${{ secrets.OSSRH_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-id: ${{ secrets.SIGNING_KEY_ID }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}

      - name: Commit changes
        if: steps.bump-module-version.outputs.version != ''
        run: |
          git config user.name \"Raxden Robot\"
          git config user.email "raxden.dev@gmail.com"
          git add .
          git commit -m "Bump ${{ matrix.module  }} version to ${{ steps.bump-module-version.outputs.version }} [skip ci]"
          git pull --ff-only
        shell: bash

      - name: Push changes
        if: steps.bump-module-version.outputs.version != ''
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CI_GIT_TOKEN }}
          force: true

  status:
    needs: [ publish ]
    if: success()
    name: Status
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4