# This is a basic workflow to help you get started with Actions

name: Publish library

# Workflow events: Controls when the action will run.
# More info: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    types:
      - closed
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Enable debug for the `gradle-build-action` cache operations
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  info:
    name: Preliminary Information
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Basic Information
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event with ${{ github.event.action }} action."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "  "
          echo "github.ref = ${{ github.ref }}"
          echo "github.sha = ${{ github.sha }}"
          echo "github.event.pull_request.base.ref = ${{ github.event.pull_request.base.ref }}"
          echo "github.event.pull_request.labels = ${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "  "

  publish:
    name: Publish to Sonatype
    runs-on: ubuntu-latest
    environment: release_environment
    strategy:
      matrix:
        module: [
          android,
          android-test,
          core,
          coroutines,
          coroutines-test,
          glide,
          okhttp3,
          pagination,
          pagination-co,
          pagination-rx,
          permissions,
          preferences,
          retrofit,
          retrofit-co,
          retrofit-rx,
          rx,
          rx-test,
          threeten
        ]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup machine
        uses: ./.github/actions/common_setup

      - name: Get specific changed files in ${{ matrix.module }}
        id: changed-files-specific_library
        uses: tj-actions/changed-files@v35
        with:
          files: |
            libraries/${{ matrix.module }}/**/*

      - name: List all changed files
        if: steps.changed-files-specific_library.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the libraries/${{ matrix.module }} folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific_library.outputs.all_changed_files }}"

      - name: Increase minor version
        if: steps.changed-files-specific_library.outputs.any_changed == 'true'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: increaseMinorVersion --info

      - name: Bump version
        if: steps.changed-files-specific_library.outputs.any_changed == 'true'
        id: bump-version
        run: |
          VERSION=$(./gradlew -q getVersion | tail -n 1)
          git config user.name \"RaxdenRobot\"
          git config user.email "raxden.dev@gmail.com"
          git add .
          git commit -m "Bump version $VERSION"
          git push --force
#          git tag $VERSION
#          git push --tags
#          echo "::set-output name=version::$(echo $VERSION)"

      - name: Publish ${{ matrix.module }} library in Sonatype
        if: steps.changed-files-specific_library.outputs.any_changed == 'true'
        env:
          OSSRH_ID: ${{ secrets.OSSRH_ID }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :libraries:${{ matrix.module }}:publishToSonatype closeAndReleaseStagingRepository --no-configuration-cache --info --scan

#      - name: Publish GitHub Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "!(buildSrc)/**/build/libs/**"
#          tag: ${{ steps.bump-version.outputs.version }}
