# This is a basic workflow to help you get started with Actions

name: Pull Requests

# Workflow events: Controls when the action will run.
# More info: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Enable debug for the `gradle-build-action` cache operations
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  info:
    name: Preliminary Information
    runs-on: ubuntu-latest

    steps:
      - name: Basic Information build-${{ github.event.pull_request.number || github.ref }}
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event with ${{ github.event.action }} action."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "  "
          echo "github.ref = ${{ github.ref }}"
          echo "github.sha = ${{ github.sha }}"
          echo "  "

      - name: Pull request information
        if: github.event_name == 'pull_request'
        run: |
          echo "Pull request detected"
          echo "github.event.pull_request.base.ref = ${{ github.event.pull_request.base.ref }}"
          echo "github.event.pull_request.labels = ${{ toJson(github.event.pull_request.labels.*.name) }}"

  checkstyle:
    name: Check code (detekt)
    runs-on: ubuntu-latest

    steps:
      - name: Check out code ✔️
        uses: actions/checkout@v3

      - name: Setup machine ✔️
        uses: ./.github/actions/common_setup

      - name: Check code via Detekt 📝
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt --stacktrace --scan

  test-modules:
    needs: [ checkstyle ]
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ android, coroutines, pagination-co, pagination-rx, preferences, retrofit-co, threeten ]

    steps:
      - name: Check out code ✔️
        uses: actions/checkout@v3

      - name: Setup machine ✔️
        uses: ./.github/actions/common_setup

      - name: Get specific changed files in ${{ matrix.module }} ✔️
        id: changed-files-specific_library
        uses: tj-actions/changed-files@v32
        with:
          files: |
            libraries/${{ matrix.module }}/**/*

      - name: Unit tests :${{ matrix.module }} 🧪
        if: steps.changed-files-specific_library_module.outputs.any_changed == 'true'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :libraries:${{ matrix.module }}:testDebugUnitTest --stacktrace --scan
