# This is a basic workflow to help you get started with Actions

name: Pull Request

# Workflow events: Controls when the action will run.
# More info: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Enable debug for the `gradle-build-action` cache operations
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  info:
    name: Preliminary Information
    runs-on: ubuntu-latest
    environment: release_environment

    steps:
      - name: Set up secret file
        env:
          OSSRH_ID: ${{ secrets.OSSRH_ID }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          echo OSSRH_ID=$OSSRH_ID >> secrets.txt
          echo OSSRH_PASSWORD=$OSSRH_PASSWORD >> secrets.txt
          echo OSSRH_USERNAME=$OSSRH_USERNAME >> secrets.txt
          echo SIGNING_KEY=$SIGNING_KEY >> secrets.txt 
          echo SIGNING_KEY_ID=$SIGNING_KEY_ID >> secrets.txt
          echo SIGNING_PASSWORD=$SIGNING_PASSWORD >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
