name: 'Publish module to sonatype'
description: "Publish module to sonatype"
inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  module:
    description: 'Module name'
    required: true
  sonatype-id:
    description: 'OSS Repository Hosting - Id'
    required: true
  sonatype-username:
    description: 'OSS Repository Hosting - Username'
    required: true
  sonatype-password:
    description: 'OSS Repository Hosting - Password'
    required: true
  signing-key:
    description: 'Signing key'
    required: true
  signing-id:
    description: 'Signing id'
    required: true
  signing-password:
    description: 'Signing password'
    required: true
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Load assemble artifacts
      uses: actions/download-artifact@v4
      with:
        name: assembleRelease-${{ inputs.id }}

    - name: Publish ${{ inputs.module }} module in Sonatype
      env:
        OSSRH_ID: ${{ inputs.sonatype-id }}
        OSSRH_PASSWORD: ${{ inputs.sonatype-password }}
        OSSRH_USERNAME: ${{ inputs.sonatype-username }}
        SIGNING_KEY: ${{ inputs.signing-key }}
        SIGNING_KEY_ID: ${{ inputs.signing-id }}
        SIGNING_PASSWORD: ${{ inputs.signing-password }}
      run: |
        ./gradlew :${{ inputs.module }}:publishToSonatype closeAndReleaseStagingRepository --no-configuration-cache --scan
      shell: bash
