name: 'Publish module to sonatype'
description: "Publish module to sonatype"
inputs:
  id:
    description: 'Value used to identify the workflow run'
    required: false
    default: ${{ github.run_number }}
  module:
    description: 'Module name'
    required: true
  sonatype-id:
    description: 'OSS Repository Hosting - Id'
    required: true
  sonatype-username:
    description: 'OSS Repository Hosting - Username'
    required: true
  sonatype-password:
    description: 'OSS Repository Hosting - Password'
    required: true
  signing-key:
    description: 'Signing key'
    required: true
  signing-id:
    description: 'Signing id'
    required: true
  signing-password:
    description: 'Signing password'
    required: true
outputs: { }
runs:
  using: "composite"
  steps:
    - name: Get specific changed files in ${{ inputs.module }}
      id: changed-files-specific
      uses: tj-actions/changed-files@v35
      with:
        files: |
          ${{ inputs.module | replace(':', '/') }}/**/*

    - name: List all changed files
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: |
        echo "One or more files in the ${{ inputs.module | replace(':', '/') }} folder has changed."
        echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
        echo "${{ inputs.module }} module has been detected with changes" >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Publish ${{ inputs.module }} module in Sonatype
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      env:
        OSSRH_ID: ${{ inputs.sonatype-id }}
        OSSRH_PASSWORD: ${{ inputs.sonatype-password }}
        OSSRH_USERNAME: ${{ inputs.sonatype-username }}
        SIGNING_KEY: ${{ inputs.signing-key }}
        SIGNING_KEY_ID: ${{ inputs.signing-id }}
        SIGNING_PASSWORD: ${{ inputs.signing-password }}
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: :${{ inputs.module }}:publishToSonatype closeAndReleaseStagingRepository --no-configuration-cache --info --scan
